#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_FE380CG)  += simcddrv2.o
obj-$(CONFIG_FE170CSG)  += simcddrv2.o

obj-$(CONFIG_A503ML)  += simcddrv.o
 obj-$(CONFIG_FE171CG)  += simcddrv2.o

