#
#  Copyright (c) 2013, ASUSTek, Inc. All Rights Reserved.
#  Written by chris chang chris1_chang@asus.com
#

obj-$(CONFIG_ASUS_ENGINEER_MODE) += asus_battery_proc_fs_asustag.o \
                                    asus_battery_power.o \
                                    asus_battery_proc_fs.o

obj-$(CONFIG_ME372CG_BATTERY_BQ27520) += bq27520_battery_core.o    \
                                         bq27520_factory_data.o    \
                                         bq27520_proc_fs.o         \
                                         bq27520_proc_fs_asustag.o \
                                         bq27520_battery_upt_i2c.o

